config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers:{
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in" => "user/sessions#guest_sign_in"
  end

  namespace :admin do
    root to: "mutters#index"
    get "search" => "searches#search"
    resources :mutters, only: [:index, :destroy]
    resources :users, only: [:index, :update]
    resources :comments, only: [:index, :destroy]
  end

  scope module: :user do
    root to: "homes#top"
    get "search" => "searches#search"
    get "mutters/timeline"
    patch 'users/withdrawal'
    resources :records, only: [:show, :edit, :create, :destroy, :update]
    resources :mutters, only: [:index, :show, :edit, :create, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :favorites, only: [:show]
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/models/mutter.rb
class Mutter < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy
  belongs_to :user

  has_one_attached :mutter_image

  validates :mutter, presence: true, length: { maximum: 200 }

  # 検索方法分岐
  def self.looks(search, word)
    @mutter = case search
      when "perfect_match"
        Mutter.where("mutter LIKE ?","#{word}")
      when "partial_match"
        Mutter.where("mutter LIKE ?","%#{word}%")
      else
        Mutter.all
      end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/admin/mutters_controller.rb
class Admin::MuttersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
    @mutter = Mutter.new
    @user = User.where(mutter_id:@mutter)
    @mutters = Mutter.order("created_at DESC").page(params[:page]).per(10)
  end

  def destroy
    @mutter = Mutter.find(params[:id])
    @mutter.destroy
    flash[:notice] = "削除しました。"
    redirect_back(fallback_location: root_path)
  end

  private

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.order("created_at DESC").page(params[:page]).per(10)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path, notice: "削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end

end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit, :destroy]

  def create
    @mutter = Mutter.find(params[:mutter_id])
    @comment = Comment.new
    comment = current_user.comments.new(comment_params)
    comment.mutter_id = @mutter.id
    comment.save
  end

  def destroy
    @mutter = Mutter.find(params[:mutter_id])
    @comment = Comment.new
    Comment.find(params[:id]).destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :comment_image)
  end

  def ensure_correct_user
    comment = Comment.find(params[:id])
    unless comment.user == current_user
    redirect_to user_path(current_user.id), notice:"権限がありません。"
    end
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    @mutter = Mutter.find(params[:mutter_id])
    mutter = Mutter.find(params[:mutter_id])
    favorite = current_user.favorites.new(mutter_id: mutter.id)
    favorite.save
  end

  def destroy
    @mutter = Mutter.find(params[:mutter_id])
    mutter = Mutter.find(params[:mutter_id])
    favorite = current_user.favorites.find_by(mutter_id: mutter.id)
    favorite.destroy
  end

  def show
    @user = User.find(params[:id])
    @mutters = @user.favorited_mutters.order("created_at DESC").page(params[:page]).per(10)
  end

  private

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

end

app/controllers/user/mutter_comments_controller.rb
class User::MutterCommentsController < ApplicationController

 def create
   mutter = Mutter.find(params[:mutter_id])
   comment = Comment.new(comment_params)
   comment.user_id = current_user.id
   comment.mutter_id = mutter.id
   comment.save
   redirect_to mutter_path(mutter)
 end

 private

 def post_comment_params
   params.require(:comment).permit(:comment)
 end

end

app/controllers/user/mutters_controller.rb
class User::MuttersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update , :edit, :destroy]

  def index
    @users = User.all
    @user = User.where(mutter_id:@mutter)
    @mutters = Mutter.all.order("created_at DESC").page(params[:page]).per(10)
    @comment = Comment.new
  end

  def show
    @mutters = current_user.mutters
    @mutter = Mutter.find(params[:id])
    @user = @mutter.user
    @comment = Comment.new
  end

  def timeline
    @user = current_user.followings
    @users = current_user.followings.all
    @mutters = Mutter.where(user_id:@users).order("created_at DESC").page(params[:page]).per(10)
  end

  def create
    @mutter = Mutter.new(mutter_params)
    @mutter.user_id = current_user.id # user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入
    if @mutter.save
      if @mutter.mutter_image.attached?
        tags = Vision.get_image_data(@mutter.mutter_image)
        tags.each do |tag|
        @mutter.tags.create(name: tag)
        end
      end
      flash[:notice] = "投稿しました。"
      redirect_back(fallback_location: user_path(current_user.id))
    else
      flash[:alert] = "投稿に失敗しました。"
      redirect_back(fallback_location: user_path(current_user.id))
    end
  end

  def edit
    @user = current_user
    @mutter = Mutter.find(params[:id])
  end

  def update
    @mutter = Mutter.find(params[:id])
    @mutter.user_id = current_user.id # user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入
    @mutter.update(mutter_params)
    if @mutter.mutter_image.attached?
      tags = Vision.get_image_data(@mutter.mutter_image)
      tags.each do |tag|
      @mutter.tags.create(name: tag)
      end
    end
    redirect_to user_path(current_user.id), notice: "更新しました。"
  end

  def destroy
  @mutter = Mutter.find(params[:id])
  @mutter.destroy
  flash[:notice] = "削除しました。"
  redirect_back(fallback_location: root_path)
  end

  private

  def mutter_params
  params.require(:mutter).permit(:mutter, :mutter_image)
  end

  def ensure_correct_user
  mutter = Mutter.find(params[:id])
  unless mutter.user == current_user
    redirect_to user_path(current_user.id), notice: "権限がありません。"
  end
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/records_controller.rb
class User::RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update , :edit]

  def show
    @user = User.find(params[:id])
    @record = Record.new
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    from = @month.beginning_of_month.beginning_of_day
    to = @month.end_of_month.end_of_day
    @records = @user.records.where(input_date: from..to).order("input_date ASC")
    @filter_records = []
    @records.each_with_index do |record, i|
      if i == 0
        next
      end
      if record[:weight].blank?
        record[:weight] = @records[i-1][:weight]
      end
      if record[:fat].blank?
        record[:fat] = @records[i-1][:fat]
      end
      if record[:muscle].blank?
        record[:muscle] = @records[i-1][:muscle]
      end
      if record[:waist].blank?
        record[:waist] = @records[i-1][:waist]
      end
     @filter_records.push(record)
    end
  end

  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id # user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入
    if @record.save
      redirect_to record_path(current_user.id), notice: "記録しました。"
    else
      flash[:alert] = "記録に失敗しました。"
      render record_path(current_user.id)
    end
  end

  def edit
    @user = current_user
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    @record.user_id = current_user.id
    @record.update(record_params)
    redirect_to record_path(current_user.id), notice:  "更新しました。"
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to record_path(current_user.id), notice: "削除しました。"
  end

  private

  def record_params
    params.require(:record).permit(:weight, :fat, :input_date, :waist, :muscle)
  end

  def ensure_correct_user
    @record = Record.find(params[:id])
    unless @record.user == current_user
      redirect_to user_path(current_user.id), notice: "権限がありません。"
    end
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー一覧
  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings.page(params[:page]).per(10)
  end
  # フォロワー一覧
  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers.page(params[:page]).per(10)
  end

  private

end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "ユーザー名"
      @users = User.looks(params[:search], params[:word])
    else
      @mutters = Mutter.looks(params[:search], params[:word])
    end
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.birthday = "20000101"
    end
    sign_in user
    redirect_to user_path(current_user.id), notice: 'ゲストユーザーとしてログインしました。'
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

    protected

    # 退会しているかを判断するメソッド
    def user_state
      ## 【処理内容1】 入力されたemailからアカウントを1件取得
      @user = User.find_by(email: params[:user][:email])
      ## アカウントを取得できなかった場合、このメソッドを終了する
      return if !@user
      ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
      if @user.valid_password?(params[:user][:password]) && @user.is_deleted
        ## 【処理内容3】 会員のステータスが退会だったら
        redirect_to root_path
      end
    end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]
  before_action :check_guest, only: :withdrawal

  def index
    @users = User.where(is_deleted: false).order("created_at DESC").page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @mutters = @user.mutters.order("created_at DESC").page(params[:page]).per(10)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "変更しました。"
    else
      flash[:alert] = "変更に失敗しました。"
      render :edit
    end
  end

  def withdrawal
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path, notice: "退会しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :birthday, :height, :introduction, :profile_image, :is_deleted)
  end

  def ensure_correct_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user.id), notice: "権限がありません。"
    end
  end

  def check_guest
    if current_user.email == "guest@example.com"
      redirect_to edit, alert: "ゲストユーザーは削除できません。"
    end
  end

end

app/helpers/admin/mutters_helper.rb
module Admin::MuttersHelper
end

app/views/user/mutters/_mutter.html.erb
<% mutters.each do |mutter| %>

<div class="box">
  <!--投稿主情報-->
  <div style="background-color: #fff0f5;" class="border-top border-left border-right rounded-top mt-4 p-2">
    <%= link_to user_path(mutter.user.id), class:"link" do %>
      <%= image_tag mutter.user.get_profile_image, class: "rounded-circle mr-2", size: "35x35" %>
      <%= mutter.user.name %>
    <% end %>
  </div>

  <!--投稿内容-->
  <div class="border-left border-right p-3">
    <strong><%= mutter.mutter %></strong><br>
    <p class="text-center">
      <% if mutter.mutter_image.attached? %>
        <%= image_tag mutter.mutter_image, class: "rounded mt-3", width: "80%" %>
        <div class="tag-box">
          <% mutter.tags.each do |tag| %>
            <span class="label mr-1">
              <%= tag.name %>
            </span>
          <% end %>
        </div>
      <% end %>
    </p>
    <p class="text-right">
      <%= mutter.created_at.strftime("%Y/%m/%d %H:%M") %>
    </p>
  </div>

  <!--いいね・コメント・編集・削除-->
  <div class="bottom border-bottom border-left border-right rounded-bottom mb-4 pt-1 pl-3">
    <p class="pr-3" id="favorite-btn-<%= mutter.id %>">
      <%= render "user/favorites/favorite-btn", mutter: mutter %>
    </p>
    <p class="pr-3">
      <%= link_to mutter_path(mutter.id), class:"link", title:"コメントする" do %>
        <i class="fas fa-comment-alt"></i>
        <%= mutter.comments.count %>
      <% end %>
    </p>
    <% if mutter.user == current_user %>
      <p class="pr-3">
        <%= link_to edit_mutter_path(mutter), class:"link", title:"編集する" do %>
          <i class="fas fa-pen"></i>
        <% end %>
      </p>
      <p class="pr-3">
        <%= link_to mutter, class:"link", method: :delete, data: { confirm: "本当に削除しますか？" }, title:"削除する" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

<% end %>

app/views/user/mutters/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "user/users/left", user: @user %>
    </div>
    <div class="col-lg-6 px-5">
      <h4 class="mb-4">
        <strong>
          <i class="far fa-moon"></i>
          投稿の編集
        </strong>
      </h4>
      <%= form_with model:@mutter,local:true do |f| %>
      <div class="form-group text-right">
        <%= f.text_area :mutter, class: "form-control", rows: "5" %>
        <%= f.file_field :mutter_image, accept: "image/*" %>
        <%= f.submit "更新する", class: "btn btn-sm btn-success" %>
      </div>
      <% end %>
    </div>
    <div class="col-lg-3">
      <%= render "user/users/right", user: @user %>
    </div>
  </div>
</div>

app/views/user/mutters/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "user/users/left", user: current_user %>
    </div>
    <div class="col-lg-6">
      <h4>
        <strong>
          <i class="far fa-moon"></i>
          全てのつぶやき
        </strong>
      </h4>
      <%= render "user/mutters/mutter", mutters: @mutters, users: @users %>
      <%= paginate @mutters, theme: "twitter-bootstrap-4" %>
    </div>
    <div class="col-lg-3">
      <%= render "user/users/right" %>
    </div>
  </div>
</div>

app/views/user/mutters/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "user/users/left", user: @user %>
    </div>
    <div class="col-lg-6 pb-5">
      <div class="box">
        <!--投稿主情報-->
        <div style="background-color:#fff0f5;" class="border-top border-left border-right rounded-top mt-4 p-2">
          <%= link_to user_path(@mutter.user.id), class:"link" do %>
            <%= image_tag @mutter.user.get_profile_image, class: "rounded-circle", size: "35x35" %>
            <%= @mutter.user.name %>
          <% end %>
        </div>

        <!--投稿内容-->
        <div class="border-left border-right p-3">
          <strong><%= @mutter.mutter %></strong><br>
          <p class="text-center">
            <% if @mutter.mutter_image.attached? %>
              <%= image_tag @mutter.mutter_image, class: "rounded mt-3", width: "80%" %>
              <div class="tag-box">
                <% @mutter.tags.each do |tag| %>
                  <span class="label mr-1">
                    <%= tag.name %>
                  </span>
                <% end %>
              </div>
            <% end %>
          </p>
          <p class="text-right">
            <%= @mutter.created_at.strftime("%Y/%m/%d %H:%M") %>
          </p>
        </div>

        <!--いいね・コメント-->
        <div class="bottom border-bottom border-left border-right rounded-bottom pt-1 pr-1 mb-5">
          <p class="pr-3" id="favorite-btn-<%= @mutter.id %>">
            <%= render "user/favorites/favorite-btn", mutter: @mutter %>
          </p>
          <p class="pr-3">
            <%= link_to mutter_path(@mutter.id), class:"link", title:"コメントする" do %>
              <i class="fas fa-comment-alt"></i>
              <span id="comment_count">
                <%= render "user/comments/count", mutter: @mutter %>
              </span>
            <% end %>
          </p>
        </div>

        <!--コメント機能-->
        <div id="comments-area">
          <div class="mb-5 text-right actions">
            <%= form_with model: [@mutter, @comment], local: false do |f| %>
              <%= f.text_area :comment, class: "form-control", placeholder: "コメントの内容"%>
              <%= f.file_field :comment_image, accept: "image/*" %>
              <%= f.submit "送信", class: "btn btn-sm btn-success" %>
            <% end %>
          </div>
          <%= render "user/comments/comment", mutter: @mutter, comment: @comment %>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <%= render "user/users/right", user: @user %>
    </div>
  </div>
</div>

app/views/user/mutters/timeline.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "user/users/left", user: current_user %>
    </div>
    <div class="col-lg-6">
      <h4>
        <strong>
          <i class="far fa-moon"></i>
          フォローしているユーザーのつぶやき
        </strong>
      </h4>
      <%= render "user/mutters/mutter", mutters: @mutters %>
      <%= paginate @mutters, theme: "twitter-bootstrap-4" %>
    </div>
    <div class="col-lg-3">
      <%= render "user/users/right" %>
    </div>
  </div>
</div>